from __future__ import annotations

from employee_runtime.workflow_packs.base import WorkflowPack, WorkflowPackEvaluationCase


BUILTIN_WORKFLOW_PACKS: list[WorkflowPack] = [
    WorkflowPack(
        pack_id="executive_assistant_pack",
        display_name="Executive Assistant",
        description="Handles executive scheduling, inbox triage, briefings, follow-ups, and approvals.",
        supported_lanes=[
            "communication",
            "scheduling",
            "briefing",
            "approval",
            "business_process",
        ],
        classification_hints=[
            "executive assistant",
            "calendar",
            "inbox",
            "briefing",
            "follow up",
            "meeting",
        ],
        required_tools=["email", "calendar", "messaging"],
        optional_tools=["document_ingestion", "file_storage", "crm"],
        output_templates={
            "communication": "Draft a concise response with context, decision needed, and next action.",
            "scheduling": "Summarize availability, constraints, proposed time, and confirmation status.",
            "briefing": "Prepare a prioritized executive brief with decisions, risks, and owner follow-ups.",
            "approval": "Present the requested action, rationale, risk, and approve/decline options.",
            "business_process": "Track owner, deadline, dependencies, and next checkpoint.",
        },
        autonomy_overrides={
            "external_send": "assisted",
            "calendar_modify": "assisted",
            "routine_follow_up": "full",
        },
        domain_vocabulary=[
            "briefing",
            "agenda",
            "stakeholder",
            "action item",
            "follow-up",
            "availability",
        ],
        onboarding_questions=[
            "Who does the employee support and what are their preferred communication channels?",
            "Which calendar and inbox actions can be handled without approval?",
            "What should be included in the morning briefing?",
        ],
        evaluation_cases=[
            WorkflowPackEvaluationCase(
                case_id="ea_morning_brief",
                input="Prepare tomorrow morning's briefing from today's meetings and open follow-ups.",
                expected_lane="briefing",
                required_terms=["decisions", "follow-ups", "priorities"],
            ),
            WorkflowPackEvaluationCase(
                case_id="ea_schedule_meeting",
                input="Find time next week for a customer renewal review with Finance and Sales.",
                expected_lane="scheduling",
                required_terms=["availability", "attendees", "confirmation"],
            ),
        ],
        roi_metrics={
            "default_minutes_saved": 45.0,
            "follow_up_minutes_saved": 12.0,
            "briefing_minutes_saved": 20.0,
        },
    ),
    WorkflowPack(
        pack_id="operations_coordinator_pack",
        display_name="Operations Coordinator",
        description="Coordinates cross-functional operational workflows, handoffs, status tracking, and exception escalation.",
        supported_lanes=[
            "business_process",
            "communication",
            "monitoring",
            "approval",
            "data_analysis",
        ],
        classification_hints=[
            "operations",
            "ops",
            "coordinator",
            "handoff",
            "process",
            "status",
            "vendor",
        ],
        required_tools=["email", "messaging", "custom_api"],
        optional_tools=["calendar", "crm", "file_storage", "document_ingestion"],
        output_templates={
            "business_process": "Document the workflow state, owner, blockers, next action, and escalation path.",
            "communication": "Send a status update with current state, required input, deadline, and owner.",
            "monitoring": "Report watched source, trigger condition, anomaly, impact, and recommended action.",
            "approval": "Request approval with operational impact, risk, alternatives, and rollback plan.",
            "data_analysis": "Summarize operational metrics, variance, root cause, and recommended correction.",
        },
        autonomy_overrides={
            "routine_status_update": "full",
            "vendor_commitment": "assisted",
            "process_change": "shadow",
        },
        domain_vocabulary=[
            "SLA",
            "handoff",
            "blocker",
            "runbook",
            "escalation",
            "throughput",
            "exception",
        ],
        onboarding_questions=[
            "Which operational workflows should the employee coordinate first?",
            "What systems hold workflow status and escalation data?",
            "Which exceptions require human approval before action?",
        ],
        evaluation_cases=[
            WorkflowPackEvaluationCase(
                case_id="ops_blocker_update",
                input="A vendor missed the intake SLA and three customer orders are waiting.",
                expected_lane="business_process",
                required_terms=["blocker", "owner", "escalation"],
            ),
            WorkflowPackEvaluationCase(
                case_id="ops_status_digest",
                input="Summarize today's open fulfillment issues and next actions for the team channel.",
                expected_lane="communication",
                required_terms=["status", "next action", "owner"],
            ),
        ],
        roi_metrics={
            "default_minutes_saved": 60.0,
            "status_update_minutes_saved": 15.0,
            "exception_triage_minutes_saved": 25.0,
        },
    ),
    WorkflowPack(
        pack_id="accounting_ops_pack",
        display_name="Accounting Operations",
        description="Processes accounting operations including invoice intake, reconciliation, approvals, and finance follow-ups.",
        supported_lanes=[
            "document_processing",
            "data_analysis",
            "approval",
            "communication",
            "business_process",
        ],
        classification_hints=[
            "accounting",
            "accountant",
            "finance",
            "invoice",
            "reconciliation",
            "payable",
            "receivable",
        ],
        required_tools=["email", "document_ingestion", "file_storage"],
        optional_tools=["calendar", "messaging", "custom_api", "crm"],
        output_templates={
            "document_processing": "Extract vendor, amount, due date, invoice number, discrepancies, and confidence.",
            "data_analysis": "Compare records, identify variance, cite source rows, and recommend correction.",
            "approval": "Present payment or adjustment request with amount, evidence, risk, and approver.",
            "communication": "Write a finance-safe message with invoice context, request, and deadline.",
            "business_process": "Track accounting workflow stage, missing inputs, owner, and next finance action.",
        },
        autonomy_overrides={
            "invoice_extraction": "full",
            "payment_release": "approval_required",
            "vendor_follow_up": "assisted",
        },
        domain_vocabulary=[
            "invoice",
            "GL code",
            "reconciliation",
            "accounts payable",
            "accounts receivable",
            "variance",
            "remittance",
        ],
        onboarding_questions=[
            "Which accounting workflows should be automated first?",
            "What approval thresholds apply to payments and adjustments?",
            "Where are invoices, ledgers, and vendor records stored?",
        ],
        evaluation_cases=[
            WorkflowPackEvaluationCase(
                case_id="acct_invoice_extract",
                input="Review this invoice, extract the payment details, and flag missing purchase order data.",
                expected_lane="document_processing",
                required_terms=["invoice", "amount", "purchase order"],
            ),
            WorkflowPackEvaluationCase(
                case_id="acct_reconcile_variance",
                input="Compare the ledger export against bank activity and explain the variance.",
                expected_lane="data_analysis",
                required_terms=["variance", "ledger", "source"],
            ),
        ],
        roi_metrics={
            "default_minutes_saved": 50.0,
            "invoice_processing_minutes_saved": 18.0,
            "reconciliation_minutes_saved": 30.0,
        },
    ),
    WorkflowPack(
        pack_id="legal_intake_pack",
        display_name="Legal Intake",
        description="Triages legal intake, collects facts, classifies matters, drafts summaries, and routes approvals.",
        supported_lanes=[
            "intake",
            "document_processing",
            "communication",
            "approval",
            "business_process",
        ],
        classification_hints=[
            "legal",
            "law",
            "intake",
            "matter",
            "contract",
            "compliance",
            "case",
        ],
        required_tools=["email", "document_ingestion", "file_storage"],
        optional_tools=["calendar", "messaging", "custom_api"],
        output_templates={
            "intake": "Capture parties, matter type, deadline, jurisdiction, facts, missing information, and urgency.",
            "document_processing": "Summarize document purpose, key clauses, obligations, risks, and open questions.",
            "communication": "Ask for missing legal facts with neutral language and clear response deadline.",
            "approval": "Present legal action request with context, risk tier, recommendation, and approver.",
            "business_process": "Track matter stage, owner, deadline, dependency, and escalation criteria.",
        },
        autonomy_overrides={
            "fact_collection": "full",
            "legal_recommendation": "assisted",
            "external_legal_commitment": "approval_required",
        },
        domain_vocabulary=[
            "matter",
            "jurisdiction",
            "counterparty",
            "clause",
            "obligation",
            "risk tier",
            "privilege",
        ],
        onboarding_questions=[
            "What matter types should the employee classify during intake?",
            "Which legal actions require attorney review before response?",
            "What jurisdictions, templates, and playbooks should be used?",
        ],
        evaluation_cases=[
            WorkflowPackEvaluationCase(
                case_id="legal_new_matter",
                input="A customer sent an indemnity redline and needs a response by Friday.",
                expected_lane="intake",
                required_terms=["matter", "deadline", "risk"],
            ),
            WorkflowPackEvaluationCase(
                case_id="legal_contract_summary",
                input="Summarize the key obligations in this vendor agreement for business review.",
                expected_lane="document_processing",
                required_terms=["obligations", "risks", "open questions"],
            ),
        ],
        roi_metrics={
            "default_minutes_saved": 55.0,
            "intake_triage_minutes_saved": 22.0,
            "contract_summary_minutes_saved": 35.0,
        },
    ),
]
